# Generated by Django 5.1.7 on 2025-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='Keywords',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
